#!/bin/bash

SCRIPT_DIR=$(dirname $(realpath $0))
. "$SCRIPT_DIR/_common.lib.sh"  # $BEST_VIDEO

INPUT=$1
BASE_NAME=`basename "$INPUT"`
BASE_NAME="${BASE_NAME%.*}"
SUFFIX=${INPUT##*.}

if [ "$#" -lt 3 ] ; then echo "Expecting input file, start <mm:ss>, duration <mm:ss>."; exit; fi
START=$2
STOP=$3

case "$START" in
    *:*:*) START="$START" ;;
    *:*)   START="00:$START" ;;
    *)     START="00:00:$START" ;;
esac

case "$STOP" in
    *:*:*) STOP="$STOP" ;;
    *:*)   STOP="00:$STOP" ;;
    *)     STOP="00:00:$STOP" ;;
esac

DURATION=`countTimeDiff2 "$START" "$STOP"`;

NEW_NAME="$BASE_NAME"-clip-${START//:/.}+${DURATION//:/.}.$SUFFIX

if [ "$4" == "recode" -o "$4" == "reencode" ] ; then
    CODEC="-c:a copy -c:v libx264" # -crf 18 - doesn't work with my built ffmpeg
else
    CODEC="-c copy"
fi

set -x
KEY_FRAMES="-force_key_frames 00:00:00.000"
ffmpeg -i "$INPUT" -ss "$START".0 $CODEC -t "$DURATION".0  "$NEW_NAME"
set +x

touch "$NEW_NAME" -r "$INPUT"
