#!/bin/bash

SCRIPT_DIR=$(dirname $(realpath $0))
. "$SCRIPT_DIR/_common.lib.sh"  # $BEST_VIDEO

INPUT=$1
BASE_NAME=`basename "$INPUT"`
BASE_NAME="${BASE_NAME%.*}"
SUFFIX=${INPUT##*.}

if [ "$#" < 4 ] ; then
    echo "Expecting input file, top, right, bottom, left margin as 0.0 - 1.0, ['preview']. Examples:";
    echo "'in.mp4 0.2 0.1 0 0.1  - to crop 20 % from top and 10 % from the sides.";
    exit;
fi
TOP=$2
RIGHT=$3
BOTTOM=$4
LEFT=$5

## TODO: Remove "0." from the values.

NEW_NAME="$BASE_NAME-#$TOP,$RIGHT,$BOTTOM,$LEFT.$SUFFIX";


## Also see https://incenp.org/notes/2012/video-cropping.html
## wid:hei:offX:offY
FILTER="crop=in_w*(1-$LEFT-$RIGHT):in_h*(1-$TOP-$BOTTOM):in_w*$LEFT:in_h*$TOP";

set -x
if [ "$6" == "" ] ; then
  ffplay -i "$INPUT" -vf "$FILTER"
else
  ffmpeg -i "$INPUT" -filter:v "$FILTER" $QUALITY_GOOD_H265 -c:a copy "$NEW_NAME"
  touch "$NEW_NAME" -r "$INPUT"
fi
set +x


