#!/bin/bash
set -e

#. _common.lib.sh  # $BEST_VIDEO

INPUT=$1
BASE_NAME=`basename "$INPUT"`
BASE_NAME="${BASE_NAME%.*}"
SUFFIX=${INPUT##*.}

GAMMA=$2
CONTRAST=$3

if [[ "$GAMMA"    =~ ^[0-9]+(\.[0-9]+)?$ ]] ; then echo; else echo "Usage: $0 <file> <gamma> <contrast> [<proceed>]"; exit; fi;
if [[ "$CONTRAST" =~ ^[0-9]+(\.[0-9]+)?$ ]] ; then echo; else echo "Usage: $0 <file> <gamma> <contrast> [<proceed>]"; exit; fi;

NEW_NAME="$BASE_NAME"-gm$GAMMA+ctr$CONTRAST.$SUFFIX


if [ "" == "$4" ] ; then FF=ffplay; NEW_NAME="-hide_banner"; else FF=ffmpeg; fi
## Passing -hide_banner this way is a hack.


set -x
$FF -i "$INPUT" -vf eq=gamma=$GAMMA:contrast=$CONTRAST "$NEW_NAME"
if [ "$FF" == "ffmpeg" ] ; then touch "$NEW_NAME" -r "$INPUT"; fi
## :opencl=1
set +x

