#!/bin/bash

. ~/sc/vid/_common.lib.sh

INPUT=$1
BASE_NAME=`basename "$INPUT"`
BASE_NAME="${BASE_NAME%.*}"
SUFFIX=${INPUT##*.}

if [ "$#" < 3 ] ; then echo "Expecting input file, start <mm:ss>, duration <mm:ss>."; exit; fi
START=$2
STOP=$3
#DURATION=`countTimeDiff2 "$START" "$STOP"`;

NEW_NAME="$BASE_NAME"-mute-${START//:/.}-${STOP//:/.}.$SUFFIX

#CODEC="-c:v copy -af afade=t=out:curve=hsin:st=$START:duration=$DURATION"

## Fade volume after time 10 with an annihilation period of 5 seconds:
#volume='if(lt(t,10),1,max(1-(t-10)/5,0))':eval=frame
CODEC="-c:v copy -af volume='if(lt(t,$START),1,if(lt(t,$STOP),0,1))':eval=frame"


set -x
ffmpeg -i "$INPUT" $CODEC "$NEW_NAME"
set +x

touch "$NEW_NAME" -r "$INPUT"
